name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Deploy to Droplet
        env:
          HOST: ${{ secrets.DROPLET_HOST }}
          USERNAME: ${{ secrets.DROPLET_USERNAME }}
          PRIVATE_KEY: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no $USERNAME@$HOST << 'EOF'
          cd /path/to/your/frontend_project_directory
          git pull origin main
          docker-compose -f docker-compose.prod.yml up -d --build
          EOF
