# version: "3"

# services:
#   frontend-colmed-app:
#     build: .
#     ports:
#       - "8080:8080"
#     volumes:
#       - .:/app
#       - /app/node_modules
#     environment:
#       - NODE_ENV=development
#     command: npm run dev

version: "3.8"

services:
  frontend:
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: npm run dev
