version: "3.8"

services:
  frontend:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    command: >
      /bin/sh -c "npm run build && npx http-server ./dist/spa"
